name: Endurance

on:
  schedule:
    - cron: '30 * * * *'

jobs:

  test-endurance:
    runs-on: octocore
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev
          make -j8
    - name: test-multithread (5X)
      run: |
        sudo apt-get install -y tcl8.5
        ./runtest --loopn 5 --config server-threads 3 --clients 5 --endurance

