name: Endurance

on:
  schedule:
    - cron: '*/60 * * * *'

jobs:

  test:
    runs-on: quadcore
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev
          make -j8
    - name: 'test 20x'
      run: |
        sudo apt-get install tcl8.5
        ./runtest --loopn 20

